app.py
import os
from flask import Flask
from routes import blp
from dotenv import load_dotenv
from pymongo import MongoClient

load_dotenv()



def create_app():
    app = Flask(__name__)    
    client = MongoClient(os.getenv("MONGODB_URI"))
    app.db = client.get_default_database()
    
    app.register_blueprint(blp)
    
    return app

routes.py
import datetime
import uuid
from collections import defaultdict
from flask import Blueprint, render_template, request, redirect, url_for, current_app, make_response, jsonify

blp = Blueprint("habits", __name__, template_folder="templates", static_folder="static")


def today_at_midnight():
    today = datetime.datetime.today()
    return datetime.datetime(today.year, today.month, today.day)

@blp.context_processor
def add_calc_date_range():
    def date_range(start: datetime.datetime):
        dates = [start + datetime.timedelta(days=diff) for diff in range(-3, 4)]
        return dates
    
    return  {"date_range": date_range}

@blp.route("/")
def index():
    dateStr = request.args.get("date")
    if dateStr:
        selectedDate = datetime.datetime.fromisoformat(dateStr)
    else:
        selectedDate = today_at_midnight()
    
    habitsOnDate = current_app.db.habits.find({"added": {"$lte": selectedDate}}) 
    completions = [habit["habit"] for habit in current_app.db.completions.find({"date": selectedDate})]
        
    return render_template("index.html", habits=habitsOnDate, title="Habit Tracker - Home",
                           selectedDate=selectedDate, completions=completions)
    
@blp.route("/select", methods=["GET", "POST"])
def selecting_habit():
    dateStr = request.args.get("date")
    if dateStr:
        selectedDate = datetime.datetime.fromisoformat(dateStr)
    else:
        selectedDate = today_at_midnight()
    
    habitsOnDate = current_app.db.habits.find({"added": {"$lte": selectedDate}}) 
    completions = [habit["habit"] for habit in current_app.db.completions.find({"date": selectedDate})]
        
    return render_template("delete_habit.html", habits=habitsOnDate, title="Habit Tracker - Deleting",
                           selectedDate=selectedDate, completions=completions)


@blp.route("/add", methods=["GET", "POST"])
def add_habit():
    today = today_at_midnight()
    
    if request.method == "POST":
        current_app.db.habits.insert_one({"_id": uuid.uuid4().hex, "added": today, "name": request.form.get("habit")})
        
    return render_template("add_habit.html", title="Habit Tracker - Add Habit", selectedDate=today)

@blp.route("/delete", methods=["GET", "POST"])
def delete_habit():
    selectedHabits = request.form.getlist("selected_habits")
    for habit_id in selectedHabits:
        current_app.db.habits.delete_one({"_id": habit_id})
    
    make_response(jsonify({"message": "Habit deleted successfully"}), 200)
    return redirect(url_for('.index'))


@blp.route("/complete", methods=["POST"])
def complete():
    dateString = request.form.get("date")
    habit = request.form.get("habitID")
    date = datetime.datetime.fromisoformat(dateString)
    current_app.db.completions.insert_one({"date": date, "habit": habit})
    
    return redirect(url_for("habits.index", date=dateString))

templates/add_habit.html
{% extends "layout.html" %}

{% block main_content %}
    <form class="form" method="POST">
        <textarea class="form__input" id="habit" name="habit" rows="3" placeholder="Add a new daily habit"></textarea>              
        <button type="submit" class="form__button">Submit</button>
    </form>
{% endblock %}

templates/delete_habit.html
{% extends "layout.html" %}

{% block main_content %}   
    <section class="delete-habit">
        <form action="{{ url_for('.delete_habit') }}" method="POST">
        {% for habit in habits %}
            <div class="habit-row">
                <div class="habit completed habit-column">
                    <p class="habit__name">
                        {{ habit["name"] }}
                    </p>
                    <div class="checkbox">
                        <input type="checkbox" name="selected_habits" value="{{ habit['_id'] }}" class="checkbox__delete">                   
                    </div>
                </div>
            </div>
        {% endfor %} 
        <div class="del-button">
            <button type="submit" class="button button__delete"><img src="/static/svg/trash-1-svgrepo-com.svg" alt="SVG file" class="circle-icon"></button>  
        </div>
        </form>  
    </section>
{% endblock %}

templates/index.html
{% extends "layout.html" %}

{% block main_content %}   
    <section>
        {% for habit in habits %}
            {% set completed = habit["_id"] in completions %}
            {% if completed %}
                <div class="habit completed">
                    <p class="habit__name">
                        {{ habit["name"] }}
                    </p>
                    <svg class="habit__icon" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor">
                        <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd" />
                    </svg>
                </div>
            {% else %}
                <div class="habit">
                    <form method="POST" class="habit__form" action="{{ url_for('habits.complete') }}">
                        <input type="hidden" name="habitID" value="{{ habit['_id'] }}" />
                        <input type="hidden" name="date" value="{{ selectedDate }}" />
                        <button type="submit" class="habit__button">
                            {{ habit["name"] }}
                        </button>
                    </form>
                </div>
            {% endif %}
        {% endfor %}        
    </section>
{% endblock %}

templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Inter&display=swap" />
    <link rel="stylesheet" href="{{ url_for('habits.static', filename='css/main.css') }}" />

    {% block head_content %} {% endblock%}
</head>
<body>
    <header class="header">
        <h1 class="header__logo"><a href="{{ url_for('habits.index') }}" class="header__link">Habits</a></h1>
        {% if "add" not in request.endpoint %}
            <a href="{{ url_for('habits.add_habit') }}" class="header__link">+ Add new</a>
        {% endif %}
    </header>
    <main class="main">
        <section class="dates">
            {% for date in date_range(selectedDate) %}
                <a class="dates__link {{ 'dates__link--current' if loop.index0 == 3 else '' }}" href="{{ url_for('habits.index', date=date) }}">
                    <time class="date" datetime="{{ date }}">
                        <span>{{ date.strftime("%a") }}</span>
                        <span>{{ date.strftime("%d") }}</span>
                    </time>
                </a>
            {% endfor %}
        </section>
        {% block main_content %}
        {% endblock %}
    </main>
    <footer class="footer">   
        <div class="circle-container">
            <div class="green-circle">
                <a href="{{ url_for('habits.add_habit') }}" class="button button--add">
                    <img src="/static/svg/add-stroke-svgrepo-com.svg" alt="SVG file" class="circle-icon">
                </a>
            </div>     
            <div class="red-circle">
                <a href="{{ url_for('habits.selecting_habit') }}" class="button button--trash">
                    <span><img src="/static/svg/trash-1-svgrepo-com.svg" alt="SVG file" class="circle-icon"></span>
                </a>
            </div>
        </div>      
    </footer>
    
</body>
</html>